extends SceneTree

const Workspace = preload("res://src/ui/workspaces/factory/factory_workspace.gd")
const WORLD := "earth-surface-grid"
var game: Node
var serial := 0

func _initialize() -> void:
	call_deferred("_run")

func _deploy(definition: String, origin: Vector2i, recipe: String = "") -> void:
	serial += 1
	var world: Dictionary = game.state.factory_worlds[WORLD]
	var result: Dictionary = game.execute_factory_command({"protocol_version":1,"command_id":"drone-capture-%d" % serial,"kind":"DEPLOY_BUILDING","world_id":WORLD,"base_topology_revision":int(world.topology_revision),"payload":{"definition_id":definition,"origin":{"x":origin.x,"y":origin.y},"recipe_id":recipe}})
	assert(bool(result.get("accepted", false)) and bool(result.get("result", {}).get("deployed", false)), str(result))

func _run() -> void:
	game = root.get_node("Game")
	game.persistence_enabled = false
	game.set_process(false)
	game.reset_game()
	_deploy("grid_planetary_core", Vector2i(60,76))
	# One tower kit is a visual-test fixture; all production and flights below
	# are generated by the real application and authoritative simulation.
	game.state.location_inventory("earth_orbit")["building_grid_drone_tower"] = 1
	_deploy("grid_drone_tower", Vector2i(75,62))
	_deploy("grid_surface_mine", Vector2i(40,40))
	_deploy("grid_surface_mine", Vector2i(82,40))
	_deploy("grid_arc_smelter", Vector2i(48,58), "dsp_iron_ingot")
	_deploy("grid_arc_smelter", Vector2i(92,58), "dsp_copper_ingot")
	_deploy("grid_engineering_works", Vector2i(92,78), "dsp_circuit_board")
	for step in range(55):
		game.simulation.advance(game.state, 1000.0)
	var snapshot: Dictionary = game.factory_workspace_snapshot(WORLD)
	assert(not snapshot.get("drone_shipments", []).is_empty(), "Capture must show real scheduled flights")
	var host := Control.new()
	host.size = Vector2(1920,1080)
	root.add_child(host)
	var workspace := Workspace.new()
	workspace.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	host.add_child(workspace)
	workspace.apply_snapshot(snapshot)
	workspace.call("_set_active_subworkspace", "CANVAS")
	for index in range(6):
		await process_frame
	var canvas: Control = workspace.canvas()
	canvas.focus_tile(Vector2i(78,65))
	for index in range(3):
		await process_frame
	canvas.call("_select_at", canvas.call("_world_to_screen", Vector2(78,65)))
	root.size = Vector2i(3840,2160)
	for index in range(6):
		await process_frame
	await RenderingServer.frame_post_draw
	var capture := OS.get_environment("TEMP").path_join("helios-drone-production.png")
	assert(root.get_texture().get_image().save_png(capture) == OK)
	print("PASS: real drone production capture " + capture)
	host.queue_free()
	await process_frame
	quit(0)
