class_name GameplayScenarioBuilder
extends RefCounted

# Golden Scenario files are generated by golden_path_test through ordinary
# player commands and Simulation advancement. This builder never fabricates a
# status flag: it migrates and normalizes a recorded invariant-valid state.
const SCENARIO_DIRECTORY := "res://artifacts/ui-scenarios"

var content: ContentDatabase


func _init(content_database: ContentDatabase) -> void:
	content = content_database


func available_scenarios() -> Array[String]:
	var result: Array[String] = []
	var directory := DirAccess.open(SCENARIO_DIRECTORY)
	if directory == null:
		return result
	for file_name in directory.get_files():
		if file_name.ends_with(".json"):
			result.append(file_name.trim_suffix(".json"))
	result.sort()
	return result


func load_state(scenario_id: String) -> SpaceGameState:
	if not _valid_scenario_id(scenario_id):
		return null
	var path := "%s/%s.json" % [SCENARIO_DIRECTORY, scenario_id]
	if not FileAccess.file_exists(path):
		return null
	var parsed = JSON.parse_string(FileAccess.get_file_as_string(path))
	if parsed is not Dictionary:
		return null
	var envelope := parsed as Dictionary
	if str(envelope.get("scenario_id", "")) != scenario_id or str(envelope.get("invariant_source", "")) != "normal_domain_commands_and_simulation":
		return null
	if envelope.get("state", null) is not Dictionary:
		return null
	var result := SpaceGameState.from_dictionary(envelope.get("state", {}), content.domains.keys(), content.regions)
	if result == null or not _identity_invariants_hold(result):
		return null
	return result


func activate(scenario_id: String) -> bool:
	var loaded := load_state(scenario_id)
	if loaded == null:
		return false
	Game.state = loaded
	Game.simulation.ensure_frontier_state(Game.state)
	# Scenario snapshots persist authoritative state. Rebuild the same derived
	# Location summaries a normal simulation/load refresh would expose before UI
	# assertions or screenshot capture.
	Game.simulation.refresh_location_summaries(Game.state)
	Game.state_changed.emit()
	return true


func _valid_scenario_id(scenario_id: String) -> bool:
	if scenario_id.is_empty() or ".." in scenario_id or "/" in scenario_id or "\\" in scenario_id:
		return false
	return scenario_id.is_valid_filename()


func _identity_invariants_hold(candidate: SpaceGameState) -> bool:
	var ship_ids := {}
	for ship_value in candidate.ships:
		var ship_id := str((ship_value as Dictionary).get("instance_id", ""))
		if ship_id.is_empty() or ship_ids.has(ship_id):
			return false
		ship_ids[ship_id] = true
	var route_ship_ids := {}
	for service_value in candidate.logistics_network.get("services", {}).values():
		for ship_id_value in (service_value as Dictionary).get("assigned_ship_ids", []):
			var ship_id := str(ship_id_value)
			if not ship_ids.has(ship_id) or route_ship_ids.has(ship_id):
				return false
			route_ship_ids[ship_id] = true
	return true
