[CmdletBinding()]
param(
    [string]$ProjectPath = "D:\Projects\standalone\core_gameplay_lab",
    [string]$OutputPath = "docs\ui-audit\gameplay-coverage.md"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Read-JsonFile([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return $null
    }
    return Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
}

function Escape-Cell([object]$Value) {
    return ([string]$Value).Replace("|", "\|").Replace("`r", " ").Replace("`n", " ")
}

$actionRegistryPath = Join-Path $ProjectPath "data\player_action_registry.json"
$stateEvidencePath = Join-Path $ProjectPath "artifacts\test-results\ui-state-coverage.json"
$actionEvidencePath = Join-Path $ProjectPath "artifacts\test-results\ui-action-coverage.json"
$journeyRegistryPath = Join-Path $ProjectPath "data\gameplay_journey_registry.json"
$journeyEvidencePath = Join-Path $ProjectPath "artifacts\test-results\full-gameplay-ui.json"
$absoluteOutputPath = Join-Path $ProjectPath $OutputPath

$actionsDocument = Read-JsonFile $actionRegistryPath
$statesDocument = Read-JsonFile $stateEvidencePath
$actionEvidence = Read-JsonFile $actionEvidencePath
$journeysDocument = Read-JsonFile $journeyRegistryPath
$journeyEvidence = Read-JsonFile $journeyEvidencePath

if ($null -eq $actionsDocument -or $null -eq $journeysDocument) {
    throw "Player action and Journey registries are required before coverage generation."
}

$coreActions = @($actionsDocument.actions | Where-Object { $_.coreGameplay -eq $true })
$staticActions = @($coreActions | Where-Object { $_.verified -eq $true })
$executedActionIds = @()
$strictActionIds = @()
if ($null -ne $journeyEvidence) {
    $executedActionIds = @($journeyEvidence.executionOnlyRegistryActions)
    $strictActionIds = @($journeyEvidence.strictFourCaseActionCoverage)
}
if ($null -ne $actionEvidence) {
    $strictActionIds = @($actionEvidence.fourCaseVerifiedActions)
}
$executedCoreActions = @($coreActions | Where-Object { $_.actionId -in $executedActionIds })
$strictCoreActions = @($coreActions | Where-Object { $_.actionId -in $strictActionIds })

$stateDenominator = 0
$stateNumerator = 0
$stateResults = @()
if ($null -ne $statesDocument) {
    $stateDenominator = [int]$statesDocument.denominator
    $stateNumerator = [int]$statesDocument.numerator
    $stateResults = @($statesDocument.results)
}

$coreJourneys = @($journeysDocument.journeys | Where-Object { $_.core -eq $true })
$completeJourneyIds = @()
if ($null -ne $journeyEvidence -and $journeyEvidence.journeyComplete -eq $true) {
    $completeJourneyIds = @($journeyEvidence.completedJourneyIds)
}
$completeJourneys = @($coreJourneys | Where-Object { $_.journeyId -in $completeJourneyIds })

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# UI Gameplay Coverage (generated from test evidence)")
$lines.Add("")
$lines.Add("> Generated by ``tools/generate_ui_coverage.ps1`` from registries and runtime evidence. Missing evidence is UNVERIFIED; a static UI-to-Domain mapping is not four-case Action Coverage.")
$lines.Add("")
$lines.Add("Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')")
$lines.Add("")
$lines.Add("## Core metrics")
$lines.Add("")
$lines.Add("| Metric | Result | Evidence boundary |")
$lines.Add("| --- | ---: | --- |")
$lines.Add("| Action Coverage (Success + Failure + Consequence + Persistence) | $($strictCoreActions.Count) / $($coreActions.Count) | Counted only when all four cases have real UI evidence |")
$lines.Add("| Action Execution Evidence | $($executedCoreActions.Count) / $($coreActions.Count) | Executed at least once in the Fresh Save UI-only test; not four-case coverage |")
$lines.Add("| Static UI-to-Domain Mapping | $($staticActions.Count) / $($coreActions.Count) | Static registry/source contract |")
$lines.Add("| State Coverage | $stateNumerator / $stateDenominator | Legal Domain state + visible state + explanation + useful navigation |")
$lines.Add("| Journey Coverage | $($completeJourneys.Count) / $($coreJourneys.Count) | Counted only when every registry event completes through UI |")
$lines.Add("")

$lines.Add("## Action Registry Evidence")
$lines.Add("")
$lines.Add("| Action | Static Mapping | Executed through UI | Four-case Verified |")
$lines.Add("| --- | ---: | ---: | ---: |")
foreach ($action in $coreActions) {
    $id = [string]$action.actionId
    $lines.Add("| $(Escape-Cell $id) | $(if ($action.verified) {'PASS'} else {'--'}) | $(if ($id -in $executedActionIds) {'PASS'} else {'--'}) | $(if ($id -in $strictActionIds) {'PASS'} else {'--'}) |")
}
$lines.Add("")

$lines.Add("## State Coverage by System")
$lines.Add("")
$lines.Add("| System | Verified | Total | Unverified states |")
$lines.Add("| --- | ---: | ---: | --- |")
foreach ($group in ($stateResults | Group-Object systemId | Sort-Object Name)) {
    $verified = @($group.Group | Where-Object { $_.status -eq "VERIFIED" })
    $unverified = @($group.Group | Where-Object { $_.status -ne "VERIFIED" } | ForEach-Object { $_.stateId })
    $lines.Add("| $(Escape-Cell $group.Name) | $($verified.Count) | $($group.Count) | $(Escape-Cell ($unverified -join ', ')) |")
}
$lines.Add("")

$lines.Add("## Golden Journey Coverage")
$lines.Add("")
$lines.Add("| Journey | Status | Required Events |")
$lines.Add("| --- | --- | --- |")
foreach ($journey in $coreJourneys) {
    $id = [string]$journey.journeyId
    $status = if ($id -in $completeJourneyIds) { "VERIFIED" } else { "UNVERIFIED" }
    $lines.Add("| $(Escape-Cell $id) | $status | $(Escape-Cell (@($journey.events) -join ' -> ')) |")
}
$lines.Add("")

if ($null -ne $journeyEvidence) {
$lines.Add("## Fresh Save UI-only current boundary")
    $lines.Add("")
    $lines.Add("- Claim: ``$(Escape-Cell $journeyEvidence.claim)``")
    $lines.Add("- Highest verified milestone: ``$(Escape-Cell $journeyEvidence.highestVerifiedMilestone)``")
    $lines.Add("- Journey complete: ``$($journeyEvidence.journeyComplete)``")
    $lines.Add("- Unverified mandatory milestones: $(Escape-Cell (@($journeyEvidence.unverifiedMandatoryMilestones) -join ', '))")
    $lines.Add("")
}

$outputDirectory = Split-Path -Parent $absoluteOutputPath
[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[System.IO.File]::WriteAllText($absoluteOutputPath, ($lines -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))

Write-Host "UI_COVERAGE_GENERATED action=$($strictCoreActions.Count)/$($coreActions.Count) state=$stateNumerator/$stateDenominator journey=$($completeJourneys.Count)/$($coreJourneys.Count) output=$absoluteOutputPath"
